[package]
name = "bugi"
version = "0.1.0"
authors = ["Xanzis <xander@hughes-family.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
